import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'


export default function Home() {

  const [email, setEmail] = useState('');

  const handleSubmit = async (e) => {

    e.preventDefault();

    fetch('/api/create-account', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ email: email })
    })
    .then(res => res.json())
    .then(data => console.log(data));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Enter email</h1>
        <form onSubmit={handleSubmit}>
          <input type="text" name="email" value={email} onChange={e => setEmail(e.target.value)} />
          <button>Submit</button>
        </form>
      </main>
    </div>
  )

}
